---
- name: install Node.js
  become: yes
  apt: name={{ item }} state=installed
  with_items:
    - nodejs
    - npm

- name: nmp cache clean
  command: npm cache clean

- name: install n command
  become: yes
  command: npm install n -g

- name: install node v6.10.0
  become: yes
  command: n 6.10.0
